apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: ocp4-vmware
  namespace: clusters
spec:
  baseDomain: smoad.net`
  clusterName: ocp4
  platform:
    vsphere:
      vCenter: vcenter.smoad.net
      username: administrator@vsphere.local
      password: Iamgood@whatido1
      datacenter: Datacenter
      defaultDatastore: Datastore2
      network: VM_Network
      apiVIP: 192.168.1.25
      ingressVIP: 192.168.1.26
  pullSecretRef:
    name: pull-secret
  provisioning:
    installConfigSecretRef:
      name: install-config
  clusterInstallRef:
    group: hive.openshift.io
    kind: ClusterInstall
    name: ocp4-install
