apiVersion: operator.openshift.io/v1
kind: Config
metadata:
  name: cluster
  namespace: openshift-image-registry
spec:
  managementState: {{ .Values.managementState }}
  nodeSelector:
    node-role.kubernetes.io/infra: ""
  tolerations:
    {{- toYaml .Values.tolerations | nindent 4 }}
