{{- if .Values.central.create }}
apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: stackrox-central
  namespace: {{ .Values.global.namespace }}
spec:
  persistence:
    persistentVolumeClaim:
      claimName: central-db
  route:
    enabled: {{ .Values.central.expose.route }}
{{- end }}

