{{- if .Values.securedCluster.create }}
apiVersion: platform.stackrox.io/v1alpha1
kind: SecuredCluster
metadata:
  name: secured-cluster
  namespace: {{ .Values.global.namespace }}
spec:
  auditLogs:
    collection: Auto
  admissionControl:
    bypass: BreakGlassAnnotation
    enabled: true
{{- end }}
