apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-install
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/sanyaoluo/cluster.git'
    targetRevision: main
    path: applications/acm-subscription
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: open-cluster-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
