ingressController:
  name: default
  namespace: openshift-ingress-operator
  nodePlacement:
    nodeSelector:
      matchLabels:
        node-role.kubernetes.io/infra: ""
    tolerations:
      - key: "node-role.kubernetes.io/infra"
        effect: "NoSchedule"
