apiVersion: logging.openshift.io/v1
kind: ClusterLogging
metadata:
  name: {{ .Values.clusterLogging.name }}
  namespace: {{ .Values.clusterLogging.namespace }}
spec:
  collection:
    type: vector
  logStore:
    elasticsearch:
      resources:
        requests:
          memory: 2Gi
      storage:
        size: {{ .Values.clusterLogging.logStore.storageSize }}
      nodeCount: {{ .Values.clusterLogging.logStore.nodeCount }}
      redundancyPolicy: SingleRedundancy
    retentionPolicy:
      application:
        maxAge: {{ .Values.clusterLogging.retention.applicationMaxAge }}
    type: elasticsearch
  visualization:
    kibana:
      replicas: {{ .Values.clusterLogging.visualization.kibanaReplicas }}
    type: kibana
  managementState: Managed

