apiVersion: elasticsearch.openshift.io/v1
kind: Elasticsearch
metadata:
  name: elasticsearch
  namespace: {{ .Values.logging.namespace }}
spec:
  managementState: Managed
  nodeSpec:
    resources:
      requests:
        memory: {{ .Values.logging.elasticsearch.resources.requests.memory }}
        cpu: {{ .Values.logging.elasticsearch.resources.requests.cpu }}
      limits:
        memory: {{ .Values.logging.elasticsearch.resources.limits.memory }}
        cpu: {{ .Values.logging.elasticsearch.resources.limits.cpu }}
    nodeCount: {{ .Values.logging.elasticsearch.nodeCount }}
