apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fluentd-buffer
  namespace: {{ .Values.logging.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.logging.fluentd.bufferStorageVolume.size }}

