apiVersion: hive.openshift.io/v1
kind: ClusterDeployment
metadata:
  name: {{ .Values.clusterDeployment.name }}
  namespace: {{ .Values.clusterDeployment.namespace }}
spec:
  baseDomain: {{ .Values.clusterDeployment.baseDomain }}
  platform:
    vSphere:
      vCenter: {{ .Values.clusterDeployment.platform.vSphere.vCenter }}
      username: {{ .Values.clusterDeployment.platform.vSphere.username }}
      password: {{ .Values.clusterDeployment.platform.vSphere.password }}
      datacenter: {{ .Values.clusterDeployment.platform.vSphere.datacenter }}
      cluster: {{ .Values.clusterDeployment.platform.vSphere.cluster }}
      network: {{ .Values.clusterDeployment.platform.vSphere.network }}
      folder: {{ .Values.clusterDeployment.platform.vSphere.folder }}
      resourcePool: {{ .Values.clusterDeployment.platform.vSphere.resourcePool }}
      template: {{ .Values.clusterDeployment.platform.vSphere.template }}
  apiVIP: {{ .Values.clusterDeployment.apiVIP }}
  ingressVIP: {{ .Values.clusterDeployment.ingressVIP }}
  pullSecretRef:
    name: pull-secret
  sshKey:
    {{ .Values.clusterDeployment.sshKey | nindent 6 }}
