apiVersion: v1
baseDomain: {{ .Values.baseDomain }}
metadata:
  name: {{ .Values.clusterName }}
compute:
- name: worker
  replicas: 3
controlPlane:
  name: master
  replicas: 3
platform:
  vsphere:
    vCenter: {{ .Values.vmware.vCenter }}
    datacenter: {{ .Values.vmware.datacenter }}
    defaultDatastore: {{ .Values.vmware.datastore }}
    network: {{ .Values.vmware.network }}
    apiVIP: {{ .Values.apiVIP }}
    ingressVIP: {{ .Values.ingressVIP }}
pullSecret: {{ .Values.pullSecret }}
sshKey: {{ .Values.sshKey }}

