apiVersion: v1
kind: Secret
metadata:
  name: pull-secret
  namespace: {{ .Values.clusterDeployment.namespace }}
type: Opaque
data:
  .dockerconfigjson: {{ .Values.clusterDeployment.pullSecret | b64enc }}
