apiVersion: platform.stackrox.io/v1alpha1
kind: Central
metadata:
  name: walelab
  namespace: stackrox
spec:
  configAsCode:
    configAsCodeComponent: Enabled
  monitoring:
    openshift:
      enabled: true
  network:
    policies: Enabled
  central:
    notifierSecretsEncryption:
      enabled: false
    exposure:
      loadBalancer:
        enabled: false
        port: 443
      nodePort:
        enabled: false
      route:
        enabled: true
    telemetry:
      enabled: true
    db:
      isEnabled: Default
      connectionPoolSize:
        maxConnections: 90
        minConnections: 10
      persistence:
        persistentVolumeClaim:
          claimName: central-db
      resources:
        requests:
          cpu: 2
          memory: 2
    persistence:
      persistentVolumeClaim:
        claimName: stackrox-db
  egress:
    connectivityPolicy: Online
  scannerV4:
    db:
      persistence:
        persistentVolumeClaim:
          claimName: scanner-v4-db
    indexer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
    matcher:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
    scannerComponent: Default
  scanner:
    analyzer:
      scaling:
        autoScaling: Enabled
        maxReplicas: 5
        minReplicas: 2
        replicas: 3
