apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: acm-install
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/your-repo/acm-subscription.git'
    targetRevision: HEAD
    path: .
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: open-cluster-management
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
