{{- range .Values.roleBindings }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .group }}-{{ .role }}
  namespace: {{ .namespace }}
subjects:
  - kind: Group
    name: {{ .group }}
roleRef:
  kind: ClusterRole
  name: {{ .role }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}

