apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-machineset
  namespace: openshift-gitops
spec:
  project: default
  source:
    repoURL: 'https://github.com/sanyaoluo/cluster.git'
    targetRevision: main
    path: infra-machineset-walelab
    helm:
      valueFiles:
        - walelab-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: openshift-machine-api
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

