clusterName: walelab-mtqks
namespace: openshift-machine-api

machineSet:
  name: infra-machineset
  replicas: 5
  infraNodeRole: "infra"
  vcenter:
    datacenter: walelab
    datastore: "/walelab/datastore/datastore2"
    resourcePool: "/walelab/host/walelab/Resources"
    network: "VM Network"
  failureDomains:
    - zone: "generated-zone"
      computeCluster: "/walelab/host/walelab"

