clusterName: walelab-mtqks
namespace: openshift-machine-api

machineSet:
  name: infra-machineset
  replicas: 3
  infraNodeRole: "infra"
  vcenter:
    datastore: "/walelab/datastore/datastore2"
    resourcePool: "/walelab/host/walelab/Resources"
    folder: "/walelab/vm/walelab-mtqks"
    network: "VM Network"
  failureDomains:
    - zone: "generated-zone"
      computeCluster: "/walelab/host/walelab"

